apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
spec:
  project: default
  source:
    repoURL: https://github.com/ocp-on-nerc/nerc-ocp-config.git
    targetRevision: HEAD
    path: loki/overlays/nerc-ocp-infra
  destination:
    name: nerc-ocp-infra
    namespace: openshift-operators-redhat
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false
