apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: xdmod
  labels:
    nerc.mghpcc.org/sync-policy: common
spec:
  project: default
  source:
    repoURL: https://github.com/CCI-MOC/xdmod-cntr.git
    targetRevision: HEAD
    path: k8s/overlays/nerc-ocp-infra
  destination:
    name: nerc-ocp-infra
    namespace: xdmod
