apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  labels:
    nerc.mghpcc.org/sync-policy: common
spec:
  project: default
  source:
    repoURL: https://github.com/ocp-on-nerc/nerc-ocp-config.git
    targetRevision: HEAD
    path: vault/overlays/nerc-ocp-infra
  destination:
    name: nerc-ocp-infra
    namespace: vault
